# -*- coding: utf-8 -*-
"""Sales_Dashboard_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11772xQ1RCQBwQb_3IvliHm5Qep6Yfpx3

Milestone 7: Sales Dashboard Project
"""

import pandas as pd
df = pd.read_csv('../sales_data.csv')
#data table check
df.head()

df.dtypes

#📅converting date column to real date time format
df["date"] = pd.to_datetime(df["date"])
df.dtypes

#setting date as an index in the table
df.set_index("date",inplace=True)

#format verification
df.head()

# Group the data by month and sum the revenue
monthly_revenue = df["revenue"].resample("M").sum()

#group the data by month and sum the quantity
monthly_quantity = df["quantity"].resample("M").sum()

#month wise quantity and month wise revenue
print("📈Monthly revenue : ")
print(monthly_revenue)
print("\n📦Monthly quantity : ")
print(monthly_quantity)

#visualization of data using matplotlib
import matplotlib.pyplot as plt

plt.style.use("seaborn-v0_8-darkgrid") # Changed to a valid seaborn style
plt.figure(figsize=(10,5))
monthly_revenue.plot(marker='o', color="royalblue")
plt.title("📈Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue ($)")
plt.grid(True)
plt.tight_layout()
plt.show()

#graph of monthly quantity sold
plt.figure(figsize=(10, 5))
monthly_quantity.plot(marker='s', color='seagreen')
plt.title("📦 Monthly Quantity Sold")
plt.xlabel("Month")
plt.ylabel("Units Sold")
plt.grid(True)
plt.tight_layout()
plt.show()