# -*- coding: utf-8 -*-
"""Sales_Dashboard_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11772xQ1RCQBwQb_3IvliHm5Qep6Yfpx3

Milestone 7: Sales Dashboard Project
"""

import pandas as pd
df = pd.read_csv('/sales_data.csv')
#data table check
df.head()

df.dtypes

#📅converting date column to real date time format
df["date"] = pd.to_datetime(df["date"])
df.dtypes

#setting date as an index in the table
df.set_index("date",inplace=True)

#format verification
df.head()